//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityWs.SecuritySoap")]
    public interface SecuritySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckUserPassword(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsUserExist(string domain, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserExist", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsUserExistAsync(string domain, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserBelongToGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsUserBelongToGroup(string UserName, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserBelongToGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsUserBelongToGroupAsync(string UserName, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserEmail(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUserEmailAsync(string UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SecuritySoapChannel : SecurityWs.SecuritySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SecuritySoapClient : System.ServiceModel.ClientBase<SecurityWs.SecuritySoap>, SecurityWs.SecuritySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecuritySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SecuritySoapClient.GetBindingForEndpoint(endpointConfiguration), SecuritySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecuritySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecuritySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecuritySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecuritySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool CheckUserPassword(string User, string Password)
        {
            return base.Channel.CheckUserPassword(User, Password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string User, string Password)
        {
            return base.Channel.CheckUserPasswordAsync(User, Password);
        }
        
        public bool IsUserExist(string domain, string username)
        {
            return base.Channel.IsUserExist(domain, username);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserExistAsync(string domain, string username)
        {
            return base.Channel.IsUserExistAsync(domain, username);
        }
        
        public bool IsUserBelongToGroup(string UserName, string GroupName)
        {
            return base.Channel.IsUserBelongToGroup(UserName, GroupName);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserBelongToGroupAsync(string UserName, string GroupName)
        {
            return base.Channel.IsUserBelongToGroupAsync(UserName, GroupName);
        }
        
        public string GetUserEmail(string UserName)
        {
            return base.Channel.GetUserEmail(UserName);
        }
        
        public System.Threading.Tasks.Task<string> GetUserEmailAsync(string UserName)
        {
            return base.Channel.GetUserEmailAsync(UserName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecuritySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SecuritySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecuritySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://knf-appl-dev3/uri_dev/KklWs/Security.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SecuritySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://knf-appl-dev3/uri_dev/KklWs/Security.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SecuritySoap,
            
            SecuritySoap12,
        }
    }
}
