//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaadotWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VaadotWs.DeductionsToVaadotSoap")]
    public interface DeductionsToVaadotSoap
    {
        
        // CODEGEN: Generating message contract since element name Internal_program_code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDeductionsToVaadot", ReplyAction="*")]
        VaadotWs.SaveDeductionsToVaadotResponse SaveDeductionsToVaadot(VaadotWs.SaveDeductionsToVaadotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDeductionsToVaadot", ReplyAction="*")]
        System.Threading.Tasks.Task<VaadotWs.SaveDeductionsToVaadotResponse> SaveDeductionsToVaadotAsync(VaadotWs.SaveDeductionsToVaadotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDeductionsToVaadotRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDeductionsToVaadot", Namespace="http://tempuri.org/", Order=0)]
        public VaadotWs.SaveDeductionsToVaadotRequestBody Body;
        
        public SaveDeductionsToVaadotRequest()
        {
        }
        
        public SaveDeductionsToVaadotRequest(VaadotWs.SaveDeductionsToVaadotRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDeductionsToVaadotRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Internal_program_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Program_Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int vaada_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string P_Type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string P_Initiator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string P_Essence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string P_Area_inGIS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Merhav;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Merhav_Answer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Merhav_Comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Area_of_disposal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Pinya_Source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Nispah_Shtahim_XML;
        
        public SaveDeductionsToVaadotRequestBody()
        {
        }
        
        public SaveDeductionsToVaadotRequestBody(string Internal_program_code, string Program_Number, int vaada_id, string P_Name, string P_Type, string P_Initiator, string P_Essence, string P_Area_inGIS, string Merhav, string Merhav_Answer, string Merhav_Comment, string Area_of_disposal, string Pinya_Source, string Nispah_Shtahim_XML)
        {
            this.Internal_program_code = Internal_program_code;
            this.Program_Number = Program_Number;
            this.vaada_id = vaada_id;
            this.P_Name = P_Name;
            this.P_Type = P_Type;
            this.P_Initiator = P_Initiator;
            this.P_Essence = P_Essence;
            this.P_Area_inGIS = P_Area_inGIS;
            this.Merhav = Merhav;
            this.Merhav_Answer = Merhav_Answer;
            this.Merhav_Comment = Merhav_Comment;
            this.Area_of_disposal = Area_of_disposal;
            this.Pinya_Source = Pinya_Source;
            this.Nispah_Shtahim_XML = Nispah_Shtahim_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDeductionsToVaadotResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDeductionsToVaadotResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaadotWs.SaveDeductionsToVaadotResponseBody Body;
        
        public SaveDeductionsToVaadotResponse()
        {
        }
        
        public SaveDeductionsToVaadotResponse(VaadotWs.SaveDeductionsToVaadotResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveDeductionsToVaadotResponseBody
    {
        
        public SaveDeductionsToVaadotResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DeductionsToVaadotSoapChannel : VaadotWs.DeductionsToVaadotSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DeductionsToVaadotSoapClient : System.ServiceModel.ClientBase<VaadotWs.DeductionsToVaadotSoap>, VaadotWs.DeductionsToVaadotSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DeductionsToVaadotSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DeductionsToVaadotSoapClient.GetBindingForEndpoint(endpointConfiguration), DeductionsToVaadotSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeductionsToVaadotSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DeductionsToVaadotSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeductionsToVaadotSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DeductionsToVaadotSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeductionsToVaadotSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaadotWs.SaveDeductionsToVaadotResponse VaadotWs.DeductionsToVaadotSoap.SaveDeductionsToVaadot(VaadotWs.SaveDeductionsToVaadotRequest request)
        {
            return base.Channel.SaveDeductionsToVaadot(request);
        }
        
        public void SaveDeductionsToVaadot(string Internal_program_code, string Program_Number, int vaada_id, string P_Name, string P_Type, string P_Initiator, string P_Essence, string P_Area_inGIS, string Merhav, string Merhav_Answer, string Merhav_Comment, string Area_of_disposal, string Pinya_Source, string Nispah_Shtahim_XML)
        {
            VaadotWs.SaveDeductionsToVaadotRequest inValue = new VaadotWs.SaveDeductionsToVaadotRequest();
            inValue.Body = new VaadotWs.SaveDeductionsToVaadotRequestBody();
            inValue.Body.Internal_program_code = Internal_program_code;
            inValue.Body.Program_Number = Program_Number;
            inValue.Body.vaada_id = vaada_id;
            inValue.Body.P_Name = P_Name;
            inValue.Body.P_Type = P_Type;
            inValue.Body.P_Initiator = P_Initiator;
            inValue.Body.P_Essence = P_Essence;
            inValue.Body.P_Area_inGIS = P_Area_inGIS;
            inValue.Body.Merhav = Merhav;
            inValue.Body.Merhav_Answer = Merhav_Answer;
            inValue.Body.Merhav_Comment = Merhav_Comment;
            inValue.Body.Area_of_disposal = Area_of_disposal;
            inValue.Body.Pinya_Source = Pinya_Source;
            inValue.Body.Nispah_Shtahim_XML = Nispah_Shtahim_XML;
            VaadotWs.SaveDeductionsToVaadotResponse retVal = ((VaadotWs.DeductionsToVaadotSoap)(this)).SaveDeductionsToVaadot(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VaadotWs.SaveDeductionsToVaadotResponse> VaadotWs.DeductionsToVaadotSoap.SaveDeductionsToVaadotAsync(VaadotWs.SaveDeductionsToVaadotRequest request)
        {
            return base.Channel.SaveDeductionsToVaadotAsync(request);
        }
        
        public System.Threading.Tasks.Task<VaadotWs.SaveDeductionsToVaadotResponse> SaveDeductionsToVaadotAsync(string Internal_program_code, string Program_Number, int vaada_id, string P_Name, string P_Type, string P_Initiator, string P_Essence, string P_Area_inGIS, string Merhav, string Merhav_Answer, string Merhav_Comment, string Area_of_disposal, string Pinya_Source, string Nispah_Shtahim_XML)
        {
            VaadotWs.SaveDeductionsToVaadotRequest inValue = new VaadotWs.SaveDeductionsToVaadotRequest();
            inValue.Body = new VaadotWs.SaveDeductionsToVaadotRequestBody();
            inValue.Body.Internal_program_code = Internal_program_code;
            inValue.Body.Program_Number = Program_Number;
            inValue.Body.vaada_id = vaada_id;
            inValue.Body.P_Name = P_Name;
            inValue.Body.P_Type = P_Type;
            inValue.Body.P_Initiator = P_Initiator;
            inValue.Body.P_Essence = P_Essence;
            inValue.Body.P_Area_inGIS = P_Area_inGIS;
            inValue.Body.Merhav = Merhav;
            inValue.Body.Merhav_Answer = Merhav_Answer;
            inValue.Body.Merhav_Comment = Merhav_Comment;
            inValue.Body.Area_of_disposal = Area_of_disposal;
            inValue.Body.Pinya_Source = Pinya_Source;
            inValue.Body.Nispah_Shtahim_XML = Nispah_Shtahim_XML;
            return ((VaadotWs.DeductionsToVaadotSoap)(this)).SaveDeductionsToVaadotAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DeductionsToVaadotSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DeductionsToVaadotSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DeductionsToVaadotSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://knf-appl-dev3/tomer_ws/wsKtNosim/DeductionsToVaadot.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DeductionsToVaadotSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://knf-appl-dev3/tomer_ws/wsKtNosim/DeductionsToVaadot.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DeductionsToVaadotSoap,
            
            DeductionsToVaadotSoap12,
        }
    }
}
