//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentomWs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentModel", Namespace="http://tempuri.org/")]
    public partial class DocumentModel : object
    {
        
        private string DocIdField;
        
        private int ProgramIdField;
        
        private System.DateTime PtihaDateField;
        
        private string DocNameField;
        
        private string DocTitleField;
        
        private string DocTypeDescField;
        
        private string DocExtField;
        
        private string TopicField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocId
        {
            get
            {
                return this.DocIdField;
            }
            set
            {
                this.DocIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProgramId
        {
            get
            {
                return this.ProgramIdField;
            }
            set
            {
                this.ProgramIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PtihaDate
        {
            get
            {
                return this.PtihaDateField;
            }
            set
            {
                this.PtihaDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DocName
        {
            get
            {
                return this.DocNameField;
            }
            set
            {
                this.DocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DocTitle
        {
            get
            {
                return this.DocTitleField;
            }
            set
            {
                this.DocTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DocTypeDesc
        {
            get
            {
                return this.DocTypeDescField;
            }
            set
            {
                this.DocTypeDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DocExt
        {
            get
            {
                return this.DocExtField;
            }
            set
            {
                this.DocExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentomWs.DocumentomSoap")]
    public interface DocumentomSoap
    {
        
        // CODEGEN: Generating message contract since element name KeyValue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocList", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentomWs.DocumentModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentomWs.DocumentModel[]))]
        DocumentomWs.GetDocListResponse GetDocList(DocumentomWs.GetDocListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocList", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentomWs.GetDocListResponse> GetDocListAsync(DocumentomWs.GetDocListRequest request);
        
        // CODEGEN: Generating message contract since element name DocId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoc", ReplyAction="*")]
        DocumentomWs.GetDocResponse GetDoc(DocumentomWs.GetDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentomWs.GetDocResponse> GetDocAsync(DocumentomWs.GetDocRequest request);
        
        // CODEGEN: Generating message contract since element name DocTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDoc", ReplyAction="*")]
        DocumentomWs.InsertDocResponse InsertDoc(DocumentomWs.InsertDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentomWs.InsertDocResponse> InsertDocAsync(DocumentomWs.InsertDocRequest request);
        
        // CODEGEN: Generating message contract since element name Path from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFolder", ReplyAction="*")]
        DocumentomWs.CreateFolderResponse CreateFolder(DocumentomWs.CreateFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentomWs.CreateFolderResponse> CreateFolderAsync(DocumentomWs.CreateFolderRequest request);
        
        // CODEGEN: Generating message contract since element name ProgramId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBaseFolder", ReplyAction="*")]
        DocumentomWs.CreateBaseFolderResponse CreateBaseFolder(DocumentomWs.CreateBaseFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBaseFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentomWs.CreateBaseFolderResponse> CreateBaseFolderAsync(DocumentomWs.CreateBaseFolderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocList", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.GetDocListRequestBody Body;
        
        public GetDocListRequest()
        {
        }
        
        public GetDocListRequest(DocumentomWs.GetDocListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object KeyValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Folder;
        
        public GetDocListRequestBody()
        {
        }
        
        public GetDocListRequestBody(object KeyValue, string Folder)
        {
            this.KeyValue = KeyValue;
            this.Folder = Folder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocListResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.GetDocListResponseBody Body;
        
        public GetDocListResponse()
        {
        }
        
        public GetDocListResponse(DocumentomWs.GetDocListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentomWs.DocumentModel[] GetDocListResult;
        
        public GetDocListResponseBody()
        {
        }
        
        public GetDocListResponseBody(DocumentomWs.DocumentModel[] GetDocListResult)
        {
            this.GetDocListResult = GetDocListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDoc", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.GetDocRequestBody Body;
        
        public GetDocRequest()
        {
        }
        
        public GetDocRequest(DocumentomWs.GetDocRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocId;
        
        public GetDocRequestBody()
        {
        }
        
        public GetDocRequestBody(string DocId)
        {
            this.DocId = DocId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.GetDocResponseBody Body;
        
        public GetDocResponse()
        {
        }
        
        public GetDocResponse(DocumentomWs.GetDocResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetDocResult;
        
        public GetDocResponseBody()
        {
        }
        
        public GetDocResponseBody(byte[] GetDocResult)
        {
            this.GetDocResult = GetDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDocRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDoc", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.InsertDocRequestBody Body;
        
        public InsertDocRequest()
        {
        }
        
        public InsertDocRequest(DocumentomWs.InsertDocRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDocRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Topic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DocType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FolderPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] DocStream;
        
        public InsertDocRequestBody()
        {
        }
        
        public InsertDocRequestBody(string DocTitle, string FileExt, string Topic, string DocType, string User, string FolderPath, byte[] DocStream)
        {
            this.DocTitle = DocTitle;
            this.FileExt = FileExt;
            this.Topic = Topic;
            this.DocType = DocType;
            this.User = User;
            this.FolderPath = FolderPath;
            this.DocStream = DocStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDocResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.InsertDocResponseBody Body;
        
        public InsertDocResponse()
        {
        }
        
        public InsertDocResponse(DocumentomWs.InsertDocResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDocResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertDocResult;
        
        public InsertDocResponseBody()
        {
        }
        
        public InsertDocResponseBody(string InsertDocResult)
        {
            this.InsertDocResult = InsertDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFolder", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.CreateFolderRequestBody Body;
        
        public CreateFolderRequest()
        {
        }
        
        public CreateFolderRequest(DocumentomWs.CreateFolderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFolderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProgramId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Path;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FolderName;
        
        public CreateFolderRequestBody()
        {
        }
        
        public CreateFolderRequestBody(int ProgramId, string Path, string FolderName)
        {
            this.ProgramId = ProgramId;
            this.Path = Path;
            this.FolderName = FolderName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFolderResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.CreateFolderResponseBody Body;
        
        public CreateFolderResponse()
        {
        }
        
        public CreateFolderResponse(DocumentomWs.CreateFolderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFolderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateFolderResult;
        
        public CreateFolderResponseBody()
        {
        }
        
        public CreateFolderResponseBody(string CreateFolderResult)
        {
            this.CreateFolderResult = CreateFolderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBaseFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBaseFolder", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.CreateBaseFolderRequestBody Body;
        
        public CreateBaseFolderRequest()
        {
        }
        
        public CreateBaseFolderRequest(DocumentomWs.CreateBaseFolderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBaseFolderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsNew;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ProgramId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProgramCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProgramName;
        
        public CreateBaseFolderRequestBody()
        {
        }
        
        public CreateBaseFolderRequestBody(bool IsNew, string ProgramId, string ProgramCode, string ProgramName)
        {
            this.IsNew = IsNew;
            this.ProgramId = ProgramId;
            this.ProgramCode = ProgramCode;
            this.ProgramName = ProgramName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBaseFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBaseFolderResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentomWs.CreateBaseFolderResponseBody Body;
        
        public CreateBaseFolderResponse()
        {
        }
        
        public CreateBaseFolderResponse(DocumentomWs.CreateBaseFolderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBaseFolderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateBaseFolderResult;
        
        public CreateBaseFolderResponseBody()
        {
        }
        
        public CreateBaseFolderResponseBody(string CreateBaseFolderResult)
        {
            this.CreateBaseFolderResult = CreateBaseFolderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DocumentomSoapChannel : DocumentomWs.DocumentomSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DocumentomSoapClient : System.ServiceModel.ClientBase<DocumentomWs.DocumentomSoap>, DocumentomWs.DocumentomSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocumentomSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DocumentomSoapClient.GetBindingForEndpoint(endpointConfiguration), DocumentomSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentomSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocumentomSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentomSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocumentomSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentomSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentomWs.GetDocListResponse DocumentomWs.DocumentomSoap.GetDocList(DocumentomWs.GetDocListRequest request)
        {
            return base.Channel.GetDocList(request);
        }
        
        public DocumentomWs.DocumentModel[] GetDocList(object KeyValue, string Folder)
        {
            DocumentomWs.GetDocListRequest inValue = new DocumentomWs.GetDocListRequest();
            inValue.Body = new DocumentomWs.GetDocListRequestBody();
            inValue.Body.KeyValue = KeyValue;
            inValue.Body.Folder = Folder;
            DocumentomWs.GetDocListResponse retVal = ((DocumentomWs.DocumentomSoap)(this)).GetDocList(inValue);
            return retVal.Body.GetDocListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentomWs.GetDocListResponse> DocumentomWs.DocumentomSoap.GetDocListAsync(DocumentomWs.GetDocListRequest request)
        {
            return base.Channel.GetDocListAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentomWs.GetDocListResponse> GetDocListAsync(object KeyValue, string Folder)
        {
            DocumentomWs.GetDocListRequest inValue = new DocumentomWs.GetDocListRequest();
            inValue.Body = new DocumentomWs.GetDocListRequestBody();
            inValue.Body.KeyValue = KeyValue;
            inValue.Body.Folder = Folder;
            return ((DocumentomWs.DocumentomSoap)(this)).GetDocListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentomWs.GetDocResponse DocumentomWs.DocumentomSoap.GetDoc(DocumentomWs.GetDocRequest request)
        {
            return base.Channel.GetDoc(request);
        }
        
        public byte[] GetDoc(string DocId)
        {
            DocumentomWs.GetDocRequest inValue = new DocumentomWs.GetDocRequest();
            inValue.Body = new DocumentomWs.GetDocRequestBody();
            inValue.Body.DocId = DocId;
            DocumentomWs.GetDocResponse retVal = ((DocumentomWs.DocumentomSoap)(this)).GetDoc(inValue);
            return retVal.Body.GetDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentomWs.GetDocResponse> DocumentomWs.DocumentomSoap.GetDocAsync(DocumentomWs.GetDocRequest request)
        {
            return base.Channel.GetDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentomWs.GetDocResponse> GetDocAsync(string DocId)
        {
            DocumentomWs.GetDocRequest inValue = new DocumentomWs.GetDocRequest();
            inValue.Body = new DocumentomWs.GetDocRequestBody();
            inValue.Body.DocId = DocId;
            return ((DocumentomWs.DocumentomSoap)(this)).GetDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentomWs.InsertDocResponse DocumentomWs.DocumentomSoap.InsertDoc(DocumentomWs.InsertDocRequest request)
        {
            return base.Channel.InsertDoc(request);
        }
        
        public string InsertDoc(string DocTitle, string FileExt, string Topic, string DocType, string User, string FolderPath, byte[] DocStream)
        {
            DocumentomWs.InsertDocRequest inValue = new DocumentomWs.InsertDocRequest();
            inValue.Body = new DocumentomWs.InsertDocRequestBody();
            inValue.Body.DocTitle = DocTitle;
            inValue.Body.FileExt = FileExt;
            inValue.Body.Topic = Topic;
            inValue.Body.DocType = DocType;
            inValue.Body.User = User;
            inValue.Body.FolderPath = FolderPath;
            inValue.Body.DocStream = DocStream;
            DocumentomWs.InsertDocResponse retVal = ((DocumentomWs.DocumentomSoap)(this)).InsertDoc(inValue);
            return retVal.Body.InsertDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentomWs.InsertDocResponse> DocumentomWs.DocumentomSoap.InsertDocAsync(DocumentomWs.InsertDocRequest request)
        {
            return base.Channel.InsertDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentomWs.InsertDocResponse> InsertDocAsync(string DocTitle, string FileExt, string Topic, string DocType, string User, string FolderPath, byte[] DocStream)
        {
            DocumentomWs.InsertDocRequest inValue = new DocumentomWs.InsertDocRequest();
            inValue.Body = new DocumentomWs.InsertDocRequestBody();
            inValue.Body.DocTitle = DocTitle;
            inValue.Body.FileExt = FileExt;
            inValue.Body.Topic = Topic;
            inValue.Body.DocType = DocType;
            inValue.Body.User = User;
            inValue.Body.FolderPath = FolderPath;
            inValue.Body.DocStream = DocStream;
            return ((DocumentomWs.DocumentomSoap)(this)).InsertDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentomWs.CreateFolderResponse DocumentomWs.DocumentomSoap.CreateFolder(DocumentomWs.CreateFolderRequest request)
        {
            return base.Channel.CreateFolder(request);
        }
        
        public string CreateFolder(int ProgramId, string Path, string FolderName)
        {
            DocumentomWs.CreateFolderRequest inValue = new DocumentomWs.CreateFolderRequest();
            inValue.Body = new DocumentomWs.CreateFolderRequestBody();
            inValue.Body.ProgramId = ProgramId;
            inValue.Body.Path = Path;
            inValue.Body.FolderName = FolderName;
            DocumentomWs.CreateFolderResponse retVal = ((DocumentomWs.DocumentomSoap)(this)).CreateFolder(inValue);
            return retVal.Body.CreateFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentomWs.CreateFolderResponse> DocumentomWs.DocumentomSoap.CreateFolderAsync(DocumentomWs.CreateFolderRequest request)
        {
            return base.Channel.CreateFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentomWs.CreateFolderResponse> CreateFolderAsync(int ProgramId, string Path, string FolderName)
        {
            DocumentomWs.CreateFolderRequest inValue = new DocumentomWs.CreateFolderRequest();
            inValue.Body = new DocumentomWs.CreateFolderRequestBody();
            inValue.Body.ProgramId = ProgramId;
            inValue.Body.Path = Path;
            inValue.Body.FolderName = FolderName;
            return ((DocumentomWs.DocumentomSoap)(this)).CreateFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentomWs.CreateBaseFolderResponse DocumentomWs.DocumentomSoap.CreateBaseFolder(DocumentomWs.CreateBaseFolderRequest request)
        {
            return base.Channel.CreateBaseFolder(request);
        }
        
        public string CreateBaseFolder(bool IsNew, string ProgramId, string ProgramCode, string ProgramName)
        {
            DocumentomWs.CreateBaseFolderRequest inValue = new DocumentomWs.CreateBaseFolderRequest();
            inValue.Body = new DocumentomWs.CreateBaseFolderRequestBody();
            inValue.Body.IsNew = IsNew;
            inValue.Body.ProgramId = ProgramId;
            inValue.Body.ProgramCode = ProgramCode;
            inValue.Body.ProgramName = ProgramName;
            DocumentomWs.CreateBaseFolderResponse retVal = ((DocumentomWs.DocumentomSoap)(this)).CreateBaseFolder(inValue);
            return retVal.Body.CreateBaseFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentomWs.CreateBaseFolderResponse> DocumentomWs.DocumentomSoap.CreateBaseFolderAsync(DocumentomWs.CreateBaseFolderRequest request)
        {
            return base.Channel.CreateBaseFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentomWs.CreateBaseFolderResponse> CreateBaseFolderAsync(bool IsNew, string ProgramId, string ProgramCode, string ProgramName)
        {
            DocumentomWs.CreateBaseFolderRequest inValue = new DocumentomWs.CreateBaseFolderRequest();
            inValue.Body = new DocumentomWs.CreateBaseFolderRequestBody();
            inValue.Body.IsNew = IsNew;
            inValue.Body.ProgramId = ProgramId;
            inValue.Body.ProgramCode = ProgramCode;
            inValue.Body.ProgramName = ProgramName;
            return ((DocumentomWs.DocumentomSoap)(this)).CreateBaseFolderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentomSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DocumentomSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentomSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:44314/Documentom.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DocumentomSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:44314/Documentom.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DocumentomSoap,
            
            DocumentomSoap12,
        }
    }
}
